//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NETDUINO_IP_INTEROP_H_
#define _NETDUINO_IP_INTEROP_H_

#include <TinyCLR_Interop.h>
struct Library_Netduino_IP_Interop_Netduino_IP_Interop_NetworkInterface
{
    TINYCLR_NATIVE_DECLARE(InitializeNetworkInterfaceSettings___VOID);
    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___VOID__I4);
    TINYCLR_NATIVE_DECLARE(GetNetworkInterfaceCount___STATIC__I4);
    TINYCLR_NATIVE_DECLARE(GetNetworkInterface___STATIC__OBJECT__U4);
    TINYCLR_NATIVE_DECLARE(IPAddressFromString___STATIC__U4__STRING);

    //--//

};

struct Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless
{
    TINYCLR_NATIVE_DECLARE(UpdateConfiguration___STATIC__VOID__OBJECT__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SaveAllConfigurations___STATIC__VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Netduino_IP_Interop;

#endif  //_NETDUINO_IP_INTEROP_H_
