//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Netduino_IP_Interop.h"
#include "Netduino_IP_Interop_Netduino_IP_Interop_Wireless.h"

using namespace Netduino::IP::Interop;

HRESULT Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless::UpdateConfiguration___STATIC__VOID__OBJECT__BOOLEAN( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        UNSUPPORTED_TYPE param0;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_UNSUPPORTED_TYPE( stack, 0, param0 ) );

        INT8 param1;
        TINYCLR_CHECK_HRESULT( Interop_Marshal_INT8( stack, 1, param1 ) );

        Wireless::UpdateConfiguration( param0, param1, hr );
        TINYCLR_CHECK_HRESULT( hr );
    }
    TINYCLR_NOCLEANUP();
}

HRESULT Library_Netduino_IP_Interop_Netduino_IP_Interop_Wireless::SaveAllConfigurations___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    TINYCLR_HEADER(); hr = S_OK;
    {
        Wireless::SaveAllConfigurations( hr );
        TINYCLR_CHECK_HRESULT( hr );
    }
    TINYCLR_NOCLEANUP();
}
